# Generated by Django 4.0.1 on 2022-01-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя руководителя')),
                ('second_name', models.CharField(max_length=100, verbose_name='Фамилия руководителя')),
                ('third_name', models.CharField(max_length=100, verbose_name='Отчество руководителя')),
                ('addres', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(max_length=50, verbose_name='Цена')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('payment_account', models.IntegerField(max_length=100, verbose_name='Рассчетный счет')),
                ('number', models.IntegerField(max_length=50, verbose_name='Количество')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.firms')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.products')),
            ],
        ),
    ]
